# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='test_field',
            new_name='imp_uid',
        ),
    ]
