# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationinfo',
            name='time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9시'), (datetime.time(10, 0), '10시'), (datetime.time(11, 0), '11시'), ('12', '12시'), ('13', '13시'), ('14', '14시'), ('15', '15시'), ('16', '16시'), ('17', '17시'), ('18', '18시'), ('19', '19시'), ('20', '20시'), ('21', '22시'), ('23', '23시'), ('24', '24시')]),
        ),
    ]
